import {
  Container,
  Badge,
  Link,
  List,
  ListItem,
  UnorderedList,
  Heading,
  Center,
  Button
} from '@chakra-ui/react'
import Layout from '../../components/layouts/article'
import { Title, WorkImage, Meta } from '../../components/work'
import P from '../../components/paragraph'


const Work = () => (
  <Layout title="Fractal Studios">
    <Container>
      <Title>
        Fractal Studios <Badge>2023</Badge>
      </Title>
      <P>
        A small webdesign agency.
      </P>

      <List ml={4} my={4}>
      <ListItem>
          <Meta>Website</Meta>
          <span>Visit <Link href="https://fractalstudios.be" target="_blank">
              <Button
                variant="ghost"
                colorScheme="teal"
              >
                Fractal Studios
              </Button>
            </Link>..</span>
        </ListItem>
        <ListItem>
          <Meta>Mission</Meta>
          <span>To empower businesses and individuals with online experiences through web design solutions.</span>
        </ListItem>
        <ListItem>
          <Meta>Description</Meta>
          <span>As a student-run web design agency, my mission is to provide web design solutions that empower businesses and individuals to thrive in the digital world. </span>
        </ListItem>
      </List>

      <WorkImage src="/images/works/f.png" alt="" />

      <Heading as="h4" fontSize={16} my={6}>
        <Center>Why I love Webflow</Center>
        
      </Heading>
      <span>My work is created using Webflow. Webflow offers a user-friendly interface, design flexibility, responsive capabilities, and powerful interactions. It`&apos;`s perfect for students who want to create professional websites with low coding, showcase their design skills, and gain practical web development experience.</span>
      <UnorderedList my={4}>

      <Heading as="h4" fontSize={16} my={6}>
        <Center>Latests works</Center>
      </Heading>
        <ListItem>

            <Badge mr={2}>Antwerp Racing Team</Badge>
            ART is a dedicated group of athletes who are passionate about pushing ourselves to the limit and competing at the highest level in the sport of sprinting and hurdling.
            <br></br>
            <br></br>
            The funny thing is that the image you see on the landing page was generated by Midjourney. This was a solution to avoid copyright issues with the original picture, which was nearly identical. Visit <Link href="https://antwerpracingteam.com" target="_blank">
              <Button
                variant="ghost"
                colorScheme="teal"
              >
                ART
              </Button>
            </Link>.
            <br></br>
            <br></br>
            <WorkImage src="/images/works/art.png" alt="" />
            <br></br>
        </ListItem>

        <ListItem>
          
            <Badge mr={2}>VPDesign</Badge>
            A contemporary company that combines old crafts with the most modern techniques. 
            <br></br>
            <br></br>
            VP Design is a company dedicated to the design and production of high-quality gates and metalwork for both private and commercial customers. Visit <Link href="https://vpdesign.be/" target="_blank">
              <Button
                variant="ghost"
                colorScheme="teal"
              >
                VPDesign
              </Button>
            </Link>.
            <br></br>
            <br></br>
            <WorkImage src="/images/works/vpdesign.png" alt="" />
            <br></br>
        </ListItem>

        <ListItem>
          
          <Badge mr={2}>A.H. Clean</Badge>
          A.H. Clean says: We provide friendly, high-quality, flexible, productive and honest cleanup service for all our custom. Visit <Link href="https://ah-clean.co/" target="_blank">
              <Button
                variant="ghost"
                colorScheme="teal"
              >
                A.H. Clean
              </Button>
            </Link>.
          <br></br>
          <br></br>
          <WorkImage src="/images/works/ahclean.png" alt="" />
          <br></br>
      </ListItem>
      </UnorderedList>
    </Container>
  </Layout>
)

export default Work
export { getServerSideProps } from '../../components/chakra'
